spring:
  application:
    name: pms
  datasource:
    url: jdbc:mysql://localhost:3306/dddemo?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true


  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.niit.beans


logging:
  level:
    com.example.drugmanagement: debug
    org.thymeleaf: DEBUG



