server:
  port: 8084

spring:
  config:
    import: nacos:pms-appointment-service.yaml
  application:
    name: pms-appointment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dddemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: pms
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: pms
        group: DEFAULT_GROUP
        file-extension: yaml

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.niit.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.niit: debug
    org.springframework.cloud: debug 