server:
  port: 8087

spring:
  config:
    import: nacos:pms-teacher-service.yaml
  application:
    name: pms-teacher-service
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dddemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: pms
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: pms
        group: DEFAULT_GROUP
        file-extension: yaml

# 日志配置
logging:
  level:
    com.niit.teacherservice: debug
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n" 